language: ruby
gemfile:
  - gemfiles/rails4_2.gemfile
  - gemfiles/rails5_0.gemfile
  - gemfiles/rails5_1.gemfile
  - gemfiles/rails5_2.gemfile
  - gemfiles/rails6_0.gemfile
  - Gemfile
rvm:
  - 2.5.7
  - 2.6.5
  - 2.7.0

env:
  matrix:
    - MONGODB=3.4
    - MONGODB=3.6
    - MONGODB=4.0

before_script:
  - docker run -d -p 27017:27017 mongo:${MONGODB}
  - |
    curl -LO https://github.com/ufoscout/docker-compose-wait/releases/download/2.7.3/wait
    chmod +x wait
    WAIT_HOSTS="localhost:27017" ./wait

notifications:
  email: false
bundler_args: --without development
matrix:
  exclude:
    - rvm: 2.7.0
      gemfile: gemfiles/rails4_2.gemfile
